services:
- type: web
  name: hoops-api
  runtime: python
  region: oregon          # free regions: ohio, oregon, frankfurt
  plan: free
  buildCommand: |
    pip install -r requirements.txt
    python -m playwright install --with-deps chromium
  startCommand: >
    gunicorn -w 2 -k uvicorn.workers.UvicornWorker
             --timeout 180                       # ← 3 min
             project.api.main:app
  envVars:
    - key: PYTHONUNBUFFERED
      value: "1"
